#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 Shiro Ninomiya
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>.
#
import sys
import os
import logging
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(parent_dir)
from twostkbd import KbdConfig

logger=logging.getLogger("gen_header")
logger.setLevel(logging.DEBUG)

class ArduinoKbdConfig(KbdConfig):
    KeyGpio={"k0":5, "k1":6, "k2":7, "k3":8, "k4":9, "k5":10,
             "f1":17, "f2":18, "f3":21,
             "alt":1, "ctrl":2, "shift":3, "ext":4}

class PrintHeader():
    def __init__(self, kbdconfig, outfd=sys.stdout):
        self.outfd=outfd
        self.kbdconfig=kbdconfig

    def file_head(self, fname: str):
        self.outfd.write("/*\n")
        self.outfd.write("This file is automatically generated.\n")
        self.outfd.write("Don't edit this file.\n")
        self.outfd.write("*/\n")
        self.outfd.write("#ifndef %s_H_\n" % fname.upper())
        self.outfd.write("#define %s_H_\n" % fname.upper())
        self.outfd.write("\n")

    def file_bottom(self):
        self.outfd.write("\n")
        self.outfd.write("#endif\n")

    def gpio_map(self):
        self.outfd.write("\n")
        self.outfd.write("#define KEY_GPIO_LIST {")
        for gn in ArduinoKbdConfig.KeyGpio.values():
            self.outfd.write("%d," % gn)
        self.outfd.write("}\n")
        self.outfd.write("\n")
        self.outfd.write('''
typedef enum {
	MODKEY_S=0,
	MODKEY_A,
	MODKEY_C,
	MODKEY_E,
	MODKEY_END,
} modkey_bit_t;
''')



    def keycode_enum(self, symbols):
        self.outfd.write("enum {\n")
        for s in symbols:
            self.outfd.write("\t%s,\n" % s)
        self.outfd.write("};\n")
        self.outfd.write("\n")

    def data_struct(self):
        self.outfd.write("typedef struct regk_data{\n")
        self.outfd.write("\tuint8_t rk;\n")
        self.outfd.write("\tuint8_t mks[MODKEY_END];\n")
        self.outfd.write("} regk_data_t;\n")
        self.outfd.write("\n")
        self.outfd.write("extern regk_data_t skey_table[];\n")
        self.outfd.write("\n")

class PrintSource():
    def __init__(self, kbdconfig, outfd=sys.stdout):
        self.outfd=outfd
        self.kbdconfig=kbdconfig
        self.kbdconfig.skeytable.sort(key=lambda x: (x["1st"], x["2nd"]))
        self.keycode_symbols=["KEYCODE_0",]

    def file_head(self):
        self.outfd.write("/*\n")
        self.outfd.write("This file is automatically generated.\n")
        self.outfd.write("Don't edit this file.\n")
        self.outfd.write("*/\n")
        self.outfd.write("\n")
        self.outfd.write("#include <inttypes.h>\n")
        self.outfd.write("#include \"kbdconfig.hpp\"\n")

    def key_tables(self):
        self.outfd.write("regk_data_t skey_table[]={\n")
        for td in self.kbdconfig.skeytable:
            m={}
            for i in ("shift", "alt", "ctrl", "ext"):
                if td["mkeys"][i]=="":
                    m[i]="0"
                elif len(td["mkeys"][i])==1:
                    if td["mkeys"][i]=="\\":
                        m[i]="'\\\\'"
                    elif td["mkeys"][i]=="'":
                        m[i]="'\\''"
                    else:
                        m[i]="'%s'" % td["mkeys"][i]
                else:
                    if td["mkeys"][i]=="VBAR":
                         m[i]="'|'"
                    else:
                        m[i]="KEYCODE_%s" % td["mkeys"][i]
                        self.keycode_symbols.append(m[i])

            self.outfd.write("\t{'%s',{%s,%s,%s,%s}},\n" % (
                td["key"], m["shift"], m["alt"], m["ctrl"], m["ext"]))
        self.outfd.write("};\n")



if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    logger.debug("start")
    kbdconfig=ArduinoKbdConfig()
    if kbdconfig.readconf(os.path.join("..", "config.org")):
        logger.error("can't read 'config.org'")
        sys.exit(1)
    fname="kbdconfig"
    outfh=open(fname+".hpp", "w")
    outfc=open(fname+".cpp", "w")
    pheader=PrintHeader(kbdconfig, outfh)
    psource=PrintSource(kbdconfig, outfc)

    pheader.file_head(fname)
    pheader.gpio_map()

    psource.file_head()
    psource.key_tables()
    pheader.keycode_enum(psource.keycode_symbols)
    pheader.data_struct()

    pheader.file_bottom()
    outfh.close()
    outfc.close()
